---
# tasks file for kibana-role
      - name: Upload tar.gz kibana from remote URL
        get_url:
          url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
          dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
          mode: 0755
          timeout: 60
          force: true
        register: get_kibana
        until: get_kibana is succeeded
        tags: kibana
      - name: Create directrory for kibana
        file:
          state: directory
          path: "{{ kibana_home }}"
        tags: elastic
      - name: Extract kibana in the installation directory
        become: true
        unarchive:
          copy: false
          src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
          dest: "{{ kibana_home }}"
          extra_opts: [--strip-components=1]
          creates: "{{ kibana_home }}/bin/kibana"
        tags:
          - skip_ansible_lint
          - kibana
      - name: Set environment kibana
        become: yes
        template:
          src: templates/kb.sh.j2
          dest: /etc/profile.d/kb.sh
        tags: kibana
      - name: Set conf kibana
        become: yes
        template:
          src: templates/kibanaConf.j2
          dest: "{{ kibana_home }}/config/kibana.yml"
        tags: kibana